{% set name = "pystan" %}
{% set version = "3.3.0" %}
{% set sha256sum = "44a26a88b70f9f3b0d20864fb0f72366b902b58908d6ad4360758d037c0ed3f4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - 0001-Add-compiler-flag-for-realigning-stack.patch  # [win32 and vc<14]

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - m2-patch               # [win and vc<14]
    - {{ compiler('c') }}    # [not (win and vc<14)]
    - {{ compiler('cxx') }}  # [not (win and vc<14)]

  host:
    - python
    - setuptools
    - numpy
    - cython >=0.22,!=0.25.1
    # The VS2008 build of PyStan fails with:
    # fatal error C1060: compiler is out of heap space
    # so we use the m2w64-toolchain here
    - libpython              # [win and vc<14]
    - m2w64-toolchain        # [win and vc<14]

  run:
    - {{ pin_compatible('numpy') }}
    # http://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - libpython              # [win]
    - m2w64-toolchain        # [win]
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python
    - cython >=0.22,!=0.25.1
    - matplotlib

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
