{% set name = "pystan" %}
{% set version = "3.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e6c1cdbec8b2769f134b35a19e59e6655074da0c2f807af78dc310a99a8eb79

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - poetry-core >=1.0.0

  run:
    - python
    - aiohttp >=3.6,<4.0
    - httpstan >=4.13,<5.0
    - pysimdjson >=5.0.2,<7
    - numpy >=1.19
    - clikit >=0.6,<1.0
    - marshmallow <4
    - setuptools

test:
  imports:
    - stan
    - stan.common
    - stan.fit
    - stan.model
    - stan.plugins
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
