{% set name = "pystan" %}
{% set version = "3.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e6c1cdbec8b2769f134b35a19e59e6655074da0c2f807af78dc310a99a8eb79
  skip: true  # [win or py<310]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - numpy
    - scipy
    - poetry-core >=1.0.0

  run:
    - python
    - cython >=0.22,!=0.25.1
    - clikit >=0.6,<0.7
    - simdjson >=3.2
    - aiohttp >=3.6

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
