# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "y7uG2J2djWgEwBfJzw0FuM2gIKlhJ0wDc24Yo/gzxaKZYWEPq5MMM7ElFkbeA0TgClgEdVokZ0bxP1r9cw2eD4cjVfoseUy7/wc9NSFv21HWrLMd2t8npE0+cDqnI/EADohSVeSV/k+X4e/0GdWejw5zzUKFr4MNb2ijEiIHTvICwq2xZjghBkXSESrO3nE4K0qktrkssvHMMQsG0afQI6Q1rDDrlZldIEoO38z3YwaKS91cEjf6FHG98W8WNERR0XwWDjymTBqmhGcE4zSPej5GJE8gLmtofs+Z3YOZnIj7s8mLhsF9dB0ZWVWg2p6JpxjnVQuZz0ZI7o2h6wX2ERBK7qMAaIAODFuBfnfTZN1PoCURSDX6eutIgBQIlhAozzAdb/717wbmWEohxZmnNnGXw9GvXz0QZggEmvRE3r2orrKroU0S5zaBwgxHqF19oRm1lyNj9mHHKzx24MzkGDIP2Ii2D37iTL7wOeKWTiSDlUt5Pe9oaVrbTuw2sNq7W58KfcbTdxaoDFOHMiIvYTVYUAi58IaN5CsbVrTy8JXq+vsZ0yGGc4AowbDUKv1EMCS8uGbIO061+VcBjexTbKHwXsL0VqxdAotoJCA/fw8z1LSEW6rody1Ik8NantrecFHUZeE3IG6qBsID1uGwc8vCjBgMbgFEQVHzQPLzyME="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
