travis:
  secure:
    BINSTAR_TOKEN: 531kadaSixQ3GfjF6CnKOenwLugmHn8NjjuFJU7yINEBqj+7G0N0sh624ne+G/m6PQ04iaMbKsMSv/XNKBKNMz080LGxEq6e2qwick9/zfBtRNN5FA68rtllLMt9F4m1nyTEeW+grMD/p8ym86qJnPcOKpU1+mD4KQ/YzVUGXnS5vblSR4WleHZWZ1trS5OhcfR3rwb7eBSHtiH8dJ7QMNA7jBDFcOQx7PbQezHicfihsScWN1TZhYQsqGSgO99B/G3D6FURHqv5qRig2I0UdZIZ9FTrGuwwPwBGQgUvEQCbMDTmZq7fIs7bsAFHhtpkRshvsligwB318hbnel6CHMyzf1mfiqqmA2sDdF/igihl3UjVG6VT44TOmmG4Ng/rtmReu0+5e4cpw4aWaaC9GeoUEUWLJxK8qEDWLQH/hJDieyak6YnF+r5QMh/5j/RsGGbl0Nuakr8ZSaBno8f/GrlbWUa29XWfwGL+tsDV3fTGH5delr1UMZn8sNHZiX2uwEhxR8nM8nDDPYHH9Q3YltIrqEaLpxc+a2ODok/xGuHfZzNU74N+01hkp4ORQ6jPfK9J9LZctylqTjcuKOjfBsYu3sZUGwkpmYenQqSKwe2MchtSU14JquRtKVx6/Vw1GDBftdsqOA5g7ZBHy66svpIKNTmScgeJEGkRSQl01/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
