travis:
  secure:
    BINSTAR_TOKEN: y7uG2J2djWgEwBfJzw0FuM2gIKlhJ0wDc24Yo/gzxaKZYWEPq5MMM7ElFkbeA0TgClgEdVokZ0bxP1r9cw2eD4cjVfoseUy7/wc9NSFv21HWrLMd2t8npE0+cDqnI/EADohSVeSV/k+X4e/0GdWejw5zzUKFr4MNb2ijEiIHTvICwq2xZjghBkXSESrO3nE4K0qktrkssvHMMQsG0afQI6Q1rDDrlZldIEoO38z3YwaKS91cEjf6FHG98W8WNERR0XwWDjymTBqmhGcE4zSPej5GJE8gLmtofs+Z3YOZnIj7s8mLhsF9dB0ZWVWg2p6JpxjnVQuZz0ZI7o2h6wX2ERBK7qMAaIAODFuBfnfTZN1PoCURSDX6eutIgBQIlhAozzAdb/717wbmWEohxZmnNnGXw9GvXz0QZggEmvRE3r2orrKroU0S5zaBwgxHqF19oRm1lyNj9mHHKzx24MzkGDIP2Ii2D37iTL7wOeKWTiSDlUt5Pe9oaVrbTuw2sNq7W58KfcbTdxaoDFOHMiIvYTVYUAi58IaN5CsbVrTy8JXq+vsZ0yGGc4AowbDUKv1EMCS8uGbIO061+VcBjexTbKHwXsL0VqxdAotoJCA/fw8z1LSEW6rody1Ik8NantrecFHUZeE3IG6qBsID1uGwc8vCjBgMbgFEQVHzQPLzyME=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
